name: flutter_application_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  fluttertoast: ^8.2.1
  tflite_flutter: ^0.12.1
  image: ^4.5.4
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/etudiant1.jpg
    - images/logo.jpg
    - images/team.png
    - images/wydad.svg
    - images/maroclogo.png